#!/usr/bin/env bash
[ -d  /run/systemd/system/ ] && \
systemctl stop log2ram.service log2ram-daily.timer && \
case "$1" in
  upgrade)
    exit 0
  ;;
  *)
    systemctl disable log2ram.service log2ram-daily.timer
    exit 0
  ;;
esac
