name: Show changelog
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Show changelog
      run: |
        set -x
        PACKAGE="${GITHUB_REPOSITORY##*/}"
        sudo apt-get install -y devscripts
        [ -d debian ] || mkdir debian
        [ ! -f debian/changelog ] || rm debian/changelog
        for ifs in \^ \~ \! \#; do
          git log --format=%b:%B | grep -Fq "${ifs}" || break;
        done
        ver_date_sha=$(git log \
        --format=tformat:%ad${ifs}%h${ifs}%aN${ifs}%aE${ifs}%f${ifs}%-aD${ifs}%D \
        --date=format:%Y%m%d --reverse \
        | while IFS=${ifs} read d s n e m t x; do
          tag=$(grep -Po 'tag: [a-zA-Z]*\K[0-9a-f.]+' <<< "${x}"; :)
          last_tag=${tag:-${last_tag:-0.0}}
          dch_ver=${tag:-${last_tag}~git${d}.${s}}
          if grep -q "(${dch_ver})" debian/changelog 2>/dev/null; then
            continue
          else
            NAME=${n} EMAIL=${e} dch ${first---create --package ${PACKAGE}} ${first+-b} -v ${dch_ver} "${m//-/ }"
            sed -i '1s/UNRELEASED/unstable/g;0,/\(>  \).*/s//\1'"${t}"'/g' debian/changelog
            first=''
            [ -z "${VERSION}" ] || case "${dch_ver}" in
            "${VERSION}")
              echo "${dch_ver}${ifs}${d}${ifs}${s}"
              break
            ;;
            esac
          fi
        done)
        [ -z "${ver_date_sha}" ] || for var_name in DCH_VER GIT_DATE SHORT_SHA; do
          typeset -n v=${var_name}
          v=${ver_date_sha%%${ifs}*}
          ver_date_sha=${ver_date_sha#${v}${ifs}}
        done
        DCH_VER=${DCH_VER:-$(head -1 debian/changelog | grep -Po '(?:[a-z-]+\s)\(\K.*(?=\))')}
        GIT_DATE=${GIT_DATE:-$(git log -1 --format=%ad --date=format:%Y%m%d)}
        SHORT_SHA=${SHORT_SHA:-${GITHUB_SHA:0:7}}
        TAG_NAME=${DCH_VER//\~/.}
        for n in DCH_VER GIT_DATE SHORT_SHA TAG_NAME; do
          typeset -n v=${n}
          echo "${n}=${v}"
        done | tee -a $GITHUB_ENV
        cat debian/changelog
